function fc = fun_truss3d_fc(E,alpha,L,A,p,theta)
%FUN_TRUSS3D_FC
%    FC = FUN_TRUSS3D_FC(E,ALPHA,L,A,P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    15-Mar-2022 09:45:30

t2 = (L.*p)./2.0;
fc = [t2;t2];
