function K = fun_truss3d_K(E,alpha,L,A,p,theta)
%FUN_TRUSS3D_K
%    K = FUN_TRUSS3D_K(E,ALPHA,L,A,P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    15-Mar-2022 09:45:30

t2 = 1.0./L;
t3 = A.*E.*t2;
t4 = -t3;
K = reshape([t3,t4,t4,t3],[2,2]);
