function ft = fun_truss3d_ft(E,alpha,L,A,p,theta)
%FUN_TRUSS3D_FT
%    FT = FUN_TRUSS3D_FT(E,ALPHA,L,A,P,THETA)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    15-Mar-2022 09:45:30

t2 = A.*E.*alpha.*theta;
ft = [-t2;t2];
